// const transitionCover = document.querySelector('.transition_cover')
// const touchToggle = document.querySelector('.touch_toggle')
// const control = document.querySelector('.control')
// const controlButtons = document.querySelectorAll('.control_button')
// const wrapper = document.querySelector('.wrapper')
// const map = document.querySelector('.map')
// const mapImageContainer = document.querySelector('.map_image_container')
// const mapCover = document.querySelector('.map_cover')
// const mapImage = document.querySelector('.map_image')
// const location = document.querySelector('.location_indicator')
// const spriteContainer = document.querySelector('.sprite_container')
// const texts = document.querySelectorAll('.text')
// const sprite = document.querySelector('.sprite')
// const indicator = document.querySelector('.indicator')
// const spriteFace = document.querySelector('.face')

// maybe will use?